### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by dawdad** [geerlingguy/shelly-plug-prometheus#1]
Hello,

I don’t know if it is an error but i had it on a raspberry pi 4: 

<img width="794" alt="grafik" src="https://user-images.githubusercontent.com/703281/126661962-42f27897-6d30-4f0b-98f1-6f2819a72836.png">

I had to change the environment to the following:

![grafik](https://user-images.githubusercontent.com/703281/126662202-41c984c8-e488-4a4a-845d-49d530e218b7.png)

**Comment by geerlingguy** [comment]
Strange... I'm using the format suggested in the README in my internet-pi project:

https://github.com/geerlingguy/internet-pi/blob/master/templates/shelly-plug-docker-compose.yml.j2#L11-L14

And I can confirm it has that same format (without the list options) on my running Pi right now, and it's working fine.

I'm running:

```
pi@geerli:~/shelly-plug-prometheus $ docker-compose --version
docker-compose version 1.28.6, build unknown
```

**Comment by dawdad** [comment]
hey Jeff,

thanks for your fast response, here are my specs of the RP4:

![grafik](https://user-images.githubusercontent.com/703281/126742149-650ac0b6-b254-480a-95a6-4c3eedeb8f6c.png)

thanks for the cool php script, i will try now to extend it buy the uptime value what is a bit more complex because you need to change the URL for the Shelly.
