### ISSUE TITLE
Auth variables initialization is missing for shellygen1

### ISSUE THREAD

**Issue by pkraskov** [geerlingguy/shelly-plug-prometheus#9]
It seems like after bc8b2b5 the initialization for username and password is missing specifically for shellygen1.
Also 401 error is not properly handled so you won't know what is going on unless you debug the code.

**Comment by pkraskov** [comment]
I didn't noticed but there is a waiting pull request to solve this issue.

**Comment by geerlingguy** [comment]
Fixed!
